### ISSUE TITLE
Cannot read properties of undefined (reading 'repository')

### ISSUE THREAD

**Issue by kguidonimartins** [lucasvtiradentes/gcal-sync#84]
Thank you for this amazing package! I followed your setup guide and after running the setup I get the following error:

```
{
  "error": "Cannot read properties of undefined (reading 'repository')"
}
```
I don't have a ticktick account. Is this really necessary for everything to work?

**Comment by lucasvtiradentes** [comment]
Hi, 

no, thats not a problem! 

just disable the ticktick sync as its shown bellow:

```javascript
options: {
      syncTicktick:false,           // option to sync ticktick tasks
},
```

if you still have a problem, please send me a message on discord ;)

**Comment by kguidonimartins** [comment]
All set! Thanks!
